name: ArmourFade
main: com.relicpvp.devteam.ArmourFade
version: 1.1
authors: [Taylorsamy, superminer10]
website: http://greyvoidanimations.weebly.com/
commands:
  afgive:
    description: Gives Rainbow Armour to yourself or the player specified.
    usage: /&lt;command&gt; [player]
  afinfo:
    description: Shows plugin info.
    usage: /&lt;command&gt;
  afremove:
    description: Removes Rainbow Armour from yourself or the player specified.
    usage: /&lt;command&gt; [player]